print("save github streak")

print("streak saver")
print("streak saver")
print("streak saver")
print("streak saver")
print("streak saver")
print("streak saver")
print("streak saver")
print("streak saver")
print("hello")
print('strak saver')