print("save github streak")

print("streak saver")
print("streak saver")
print("streak saver")
print("streak saver")
print("streak saver")
print("streak saver")
print("streak saver")
print("streak saver")
print("hello")
print('strak saver')
print('strak saver')
print("streak save  r")
print("10th sep")
print("sep 1q")
print("13 sepghj")
print("streak saver 14 sep")